markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Kenrick Beckett
url: http://kenrick.me
description: .
twitter: kenrick1991
github: kenrick
gravatar_url: https://secure.gravatar.com/avatar/86f71b7b2907e160556f8f00fe940c35