# Site settings
title: Kenrick Beckett
email: contact@kenrick.me
description: The blog, projects and talks by Kenrick Beckett
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kenrick.me" # the base hostname & protocol for your site
gravatar_url: http://www.gravatar.com/avatar/86f71b7b2907e160556f8f00fe940c35


#Social media handles

twitter_url: http://twitter.com/kenrick1991
github_url:  http://github.com/kenrick
linkedin_url: http://jm.linkedin.com/in/kenrickbeckett


iams:
  - color: "#CC342D"
    sentence: I love crafting applications in Ruby
  - color: "#f39c12"
    sentence: I am enchanted by JavaScript
  - color: "#6dbd63"
    link: http://www.codedry.com
    sentence: I'm a consultant at Codedry
  - color: "#333"
    link: http://github.com/kenrick
    sentence: I'm kenrick on GitHub
  - color: "#55ACEE"
    link: http://twitter.com/kenrick1991
    sentence: I'm @kenrick1991 on Twitter

permalink:  /blog/:title.html

# Build settings
markdown: kramdown
