# Site settings
title: Kenrick Beckett
email: contact@kenrick.me
description: The blog, projects and talks by Kenrick Beckett
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kenrick.me" # the base hostname & protocol for your site
twitter_username: kenrick1991
github_username:  kenrick

# Build settings
markdown: kramdown
